# Generated by Django 3.2.9 on 2021-11-18 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_jogo', models.CharField(max_length=50)),
                ('data_lancamento', models.DateField()),
                ('sinopse', models.TextField()),
            ],
        ),
    ]
