# Generated by Django 3.2.9 on 2021-12-02 19:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('sinopse', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=500)),
                ('created_on', models.DateField(default=datetime.datetime(2021, 12, 2, 19, 40, 58, 244875, tzinfo=utc))),
                ('update_on', models.DateField()),
            ],
        ),
    ]
