# Generated by Django 3.2.9 on 2021-12-02 19:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_alter_noticia_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2021, 12, 2, 19, 43, 28, 273150, tzinfo=utc)),
        ),
    ]
