# Generated by Django 3.2.9 on 2021-12-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_alter_noticia_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='sinopse',
            field=models.TextField(),
        ),
    ]
